filters:
  events:
    campaigns: [Campaign]
    brands: [Brand, BrandPortfolio]
    areas: [Area]
    people: [CompanyUser, Team]
    event_status:
      items: [Submitted, Late, Due, Approved, Rejected]
      name: 'event_status'
    status:
      items: [Active, Inactive]
      name: 'status'
  user_tasks:
    campaigns: [Campaign]
    task_status:
      items: [Complete, Incomplete, Late]
      name: 'task_status'
    status:
      items: [Active, Inactive]
      name: 'status'
  teams_tasks:
    campaigns: [Campaign]
    task_status:
      items: [Complete, Incomplete, Late, Assigned, Unassigned]
      name: 'task_status'
    staff: [CompanyUser, Team]
    status:
      items: [Active, Inactive]
      name: 'status'
  venues:
    sliders: 
      method: venues_sliders
    price:
      items: [[1, '$'], [2, '$$'], [3, '$$$'], [4, '$$$$']]
      name: 'event_status'
    areas: [Area]
    campaigns: [Campaign]
    brands: [Brand]
  campaigns:
    brands: [Brand]
    brand_portfolios: [BrandPortfolio]
    people: [CompanyUser, Team]
    status:
      items: [Active, Inactive]
      name: 'status'
  brands:
    status:
      items: [Active, Inactive]
      name: 'status'
  company_users:
    roles: [Role]
    campaigns: [Campaign]
    teams: [Team]
    status:
      items: [Active, Inactive, Invited]
      name: 'status'
  teams:
    campaigns: [Campaign]
    status:
      items: [Active, Inactive]
      name: 'status'
  roles:
    status:
      items: [Active, Inactive]
      name: 'status'
  activity_types:
    status:
      items: [Active, Inactive]
      name: 'status'
  areas:
    status:
      items: [Active, Inactive]
      name: 'status'
  brand_portfolios:
    brands: [Brand]
    status:
      items: [Active, Inactive]
      name: 'status'
  date_ranges:
    status:
      items: [Active, Inactive]
      name: 'status'
  day_parts:
    status:
      items: [Active, Inactive]
      name: 'status'
  visits:
    custom_filter: 'DIVISIONS'  # So it's displayed first
    brand_ambassadors:
      method: brand_ambassadors_bucket
    campaigns: [Campaign]
    areas: [Area]
    cities: 
      method: cities_bucket
  activities:
    activity_types: [ActivityType]
    brands: [Brand]
    campaigns: [Campaign]
    areas: [Area]
    users: [CompanyUser]
    status:
      items: [Active, Inactive]
      name: 'status'
  results_photos:
    campaigns: [Campaign]
    brands: [Brand]
    areas: [Area]
    tags: [Tag]
    rating:
      items: [5, 4, 3, 2, 1, 0]
      name: 'rating'
    status:
      items: [Active, Inactive]
      name: 'status'
  trends:
    source: 
      method: trend_sources
    questions: 
      method: trend_questions
    campaigns: 
      method: trend_campaigns
    brands: [Brand]
    areas: [Area]