upload:
  thresholds:
  - :workers: 2
    :job_count: 15
  - :workers: 3
    :job_count: 40
  - :workers: 4
    :job_count: 80
  - :workers: 5
    :job_count: 120
  environments:
    - production
    - staging
  worker_name: uploads

export:
  thresholds:
  - :workers: 1
    :job_count: 0
  - :workers: 2
    :job_count: 1
  - :workers: 3
    :job_count: 5
  - :workers: 4
    :job_count: 8
  - :workers: 5
    :job_count: 10
  - :workers: 6
    :job_count: 12
  - :workers: 7
    :job_count: 16
  environments:
    - production
    - staging
  worker_name: exports
  min_workers: 1